name: Gradle Check
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
      - '[0-9]+.x'
  pull_request:

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  precommit-linux:
    needs: Get-CI-Image-Tag
    strategy:
      matrix:
        java: [21, 25]
    if: github.repository == 'opensearch-project/custom-codecs'
    runs-on: ubuntu-latest
    container:
      # using the same image which is used by opensearch-build team to build the OpenSearch Distribution
      # this image tag is subject to change as more dependencies and updates will arrive over time
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      options: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-options }}
    steps:
      - name: Run start commands
        run: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-command }}
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Run Gradle (check)
        run: |
          # https://github.com/opensearch-project/opensearch-build/issues/4191
          chown -R ci-runner:ci-runner `pwd`
          su ci-runner -c "source /etc/profile.d/java_home.sh && ./gradlew test check -Dorg.gradle.java.home=/opt/java/openjdk-${{ matrix.java }}"
      - name: Run Gradle (assemble)
        run: |
          # https://github.com/opensearch-project/opensearch-build/issues/4191
          chown -R ci-runner:ci-runner `pwd`
          su ci-runner -c "source /etc/profile.d/java_home.sh && ./gradlew assemble -Dorg.gradle.java.home=/opt/java/openjdk-${{ matrix.java }}"
      - name: Upload Coverage Report Artifact
        if: ${{ !cancelled() && contains(matrix.java, '21') }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jacoco-coverage-report-java${{ matrix.java }}
          path: build/reports/jacoco/test/jacocoTestReport.xml
          retention-days: 1
          if-no-files-found: error

  codecov:
    needs: precommit-linux
    if: ${{ !cancelled() && github.repository == 'opensearch-project/custom-codecs' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Download Coverage Report
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: jacoco-coverage-report-java21
          path: build/reports/jacoco/test
      - name: Upload Coverage Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  precommit-windows-macos:
    if: github.repository == 'opensearch-project/custom-codecs'
    strategy:
      matrix:
        java: [21, 25]
        os: [windows-latest, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
      - name: Run Gradle (check)
        run: |
          ./gradlew test check
      - name: Run Gradle (assemble)
        run: |
          ./gradlew assemble
